### PR TITLE
Updated dependencies and tests

### PR DESCRIPTION
**Pull request by alesguzik**
This updates Reagent, Om and ClojureScript to latest versions. As part of move to latest ClojureScript, cljx was dropped in favor of cljc files. Also https://github.com/cemerick/clojurescript.test have been deprecated, so it is replaced with native cljs.test and doo (as suggested in deprecation notice). PhantomJS shim have been dropped, as tests work just fine without it in current version of phantomjs (2.0.0). You may wish to release this update as major version.

### CODE REVIEW

**Comment by ckirkendall** [comment]
You are awesome!  I will try to get this merged this weekend.  I may switch some other things over to using doo. The setup looks a lot cleaner.

**Comment by ckirkendall** [comment]
I love this change request but unfortunately it breaks those using clojure 1.6 and below.  There are lots of people using kioo that can't upgrade at this time so I want to hold off on this.

**Comment by alesguzik** [comment]
For how long do you plan to postpone? What's wrong with releasing a major version, so those who can't upgrade won't upgrade?

**Comment by alesguzik** [comment]
And without releasing upgraded version, it holds off people like me who wish to keep their deps up to date. Some of our external components require React 13, which is supported only by Reagent 0.5.0. That's basically why I did all this upgrade. And reagent team is already workinng on adding support for React 14. There will always be people who use outdated versions. But unlike people who need new versions, they are able to just keep using the version they use now.

**Comment by ckirkendall** [comment]
I think you are right about doing a major release for 1.7.  I need to work
out some logistics on our branching but I think we can make this happen.

**Comment by alesguzik** [comment]
It's been almost 2 months since this was submitted :snail:

**Comment by alesguzik** [comment]
> I will try to get this merged this weekend.

I've submitted this 3 months ago. Since then reagent 0.6.0-alpha have been released with support for React 14, but kioo doesn't have support even for React 13, which puts this library obsolete, even though it is a cool library. Do you have plans to maintain this project at all? If you don't and if it works for you I would gladly take over maintaining kioo.

**Comment by alesguzik** [comment]
And also RC5 for Clojure 1.8.0 have been released, so mainaining support for 1.6 now makes as much sense as maintaining support for 1.0. If someone is stuck with 1.6 then he'd just use older kioo version.

**Comment by ckirkendall** [comment]
This has been merged now the 1.8 has been released.

**Pull request merged**
